services:
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  guestbook:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  jupyter:
    image: jupyter/datascience-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - jupyter_notebooks:/home/jovyan/work
      - jupyter_data:/home/jovyan/.local
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=monmotdepasse

volumes:
  redis_data:
  jupyter_notebooks:
  jupyter_data:

