FROM golang:1.19 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o guestbook main.go

FROM scratch
WORKDIR /app

COPY --from=builder /app/guestbook .

EXPOSE 3000
CMD ["./guestbook"]
