services:
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  guestbook:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis_data:
